# Generated by Django 3.2.6 on 2021-08-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='Tasa',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
